Newframework
DigitalShoestringSolutions/AirQualityMonitoring pull request #1
Opened 2023-10-25 09:19 UTC by chen2181

use new framework for air quality monitoring

2023-10-31 11:50 UTC, Greg-Hawkridge commented on airquality_dc/Dockerfile
Update Solution name and copyright year

2023-10-31 11:57 UTC, Greg-Hawkridge commented on logging/setup_logging.sh
We can remove the logging folder from individual solutions - this is tracked in a separate repository now

2023-10-31 12:03 UTC, Greg-Hawkridge requested changes

2023-10-31 12:03 UTC, Greg-Hawkridge commented on setup_commands.txt
I also think it is worth removing the setup_commands.txt as we are no longer maintaining it

2023-10-31 12:03 UTC, Greg-Hawkridge commented on logging/setup_logging.sh
We can stop including the logging file in individal solutions - it is tracked in it's own repository now

2023-10-31 12:03 UTC, Greg-Hawkridge commented on airquality_dc/Dockerfile
Update Solution name and copyright year

2023-10-31 12:03 UTC, Greg-Hawkridge commented on timeseries_sds/app.yml
Add 
`- DOCKER_INFLUXDB_INIT_RETENTION=2y`
to set influx to default retention of two years

2023-11-01 11:10 UTC, chen2181 commented on timeseries_sds/app.yml
done,. worth double check if this is in the right place,  cheers

2023-11-01 14:50 UTC, Greg-Hawkridge approved these changes

2023-11-01 15:23 UTC, merged